apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: queue-wrapper
  name: queue-wrapper
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
    nodePort: 30006
  type: NodePort
  selector:
    io.kompose.service: queue-wrapper
status:
  loadBalancer: {}
